### ISSUE TITLE
Can't Run dev-server.js

### ISSUE THREAD

**Issue by gtej** [Shapeshift-Public/ShapeShift-Skeleton#9]
When i try to run command node dev-server.js i got following error : 
Error: Cannot find module 'finalhandler'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vickydel/ShapeShift-Skeleton/dev-server.js:2:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
What should i do?

**Comment by miktam** [comment]
@gtej you have to install dependencies first: `npm install`
